# PLACEHOLDER - Generated by nixos-generate-config during install
#
# Run INSTALL_NIXOS_FROM_FLAKE.sh from minimal ISO to generate the real one.
# This file will be overwritten with actual hardware detection.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = [ "sd_mod" "sr_mod" "hv_storvsc" "hv_vmbus" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
