machine.wait_for_unit("multi-user.target")
machine.succeed("test -d /home/username/.git")
machine.succeed("cd /home/username && git status")
output = machine.succeed("cd /home/username && git log --oneline -1")
machine.log(f"Git repo initialized: {output}")
